Add an S3 processor agent
LangStream/langstream pull request #755
Opened 2024-01-21 21:48 UTC by cdbartholomew

This agent will read a single file from an S3 bucket. The name of the file to read is taken from the record.

2024-01-29 08:03 UTC, nicoloboschi reviewed
LGTM

2024-02-08 08:19 UTC, eolivelli requested changes
Overall LGTM
but I have left some minor feedback.
I think we are on our way, this agent will be very useful

Looking forward to a PR to the docs website after we commit this patch

Thanks

2024-02-08 08:19 UTC, eolivelli commented on langstream-agents/langstream-agent-s3/src/main/java/ai/langstream/agents/s3/S3Processor.java
> +        log.info("Processing file {}", fileName);
we should define what happens in case fileName is null or empty, maybe we  could "skip" the record ? (emit an empty list)

2024-02-08 08:19 UTC, eolivelli commented on langstream-agents/langstream-agent-s3/src/main/java/ai/langstream/agents/s3/S3Processor.java
> +    private static class S3SourceRecord implements Record {
we could:
1) rename this to S3ProcessorRecord
2) use the same class of the S3Source
3) switch to SimpleRecord

2024-02-08 08:19 UTC, eolivelli commented on langstream-agents/langstream-agent-s3/src/main/java/ai/langstream/agents/s3/S3Processor.java
> +        String objectName = configuration.getOrDefault("objectName", "").toString();
what about providing a sensible default, like "{{value.objectname}}" ?
ths way people don't have to bother with mustache for simple cases

2024-02-08 08:19 UTC, eolivelli commented on langstream-runtime/langstream-runtime-impl/src/main/python/pyproject.toml
> +openai = {extras = ["datalib"], version = "^1.10.0"}
this seems unrelated

2024-03-22 09:09 UTC, eolivelli reviewed
I see that this patch is accumulating changes not strictly related to the S3 Processor.
We can keep them but I would prefer to finalise the patch in this form and then follow up with other  improvements

2024-03-22 09:09 UTC, eolivelli commented on langstream-api/src/main/java/ai/langstream/api/model/ResourcesSpec.java
> +                System.err.println("Error parsing integer: " + e.getMessage());
logger ?

2024-04-01 18:13 UTC, eolivelli commented
@cdbartholomew I suggest to closed this PR, this is more a diff between this repo and the main branch of another repo.

I would prefer to merge your changes using fewer smaller patches instead of this big PR.

I will be very happy to review the single patches

2024-04-05 13:03 UTC, cdbartholomew commented
Closing for now. Will update an open a new PR.

2024-04-05 13:03 UTC, closed without merging